URI-C#/Frota-Taxi/Frota-Taxi/Models/ErrorViewModel.cs
using System;

namespace Frota_Taxi.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

URI-C#/Frota-Taxi/Frota-Taxi/Models/Frota.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Frota_Taxi.Models
{
    public class Frota
{

        public decimal alcool { get; set; }
        public decimal gasolina { get; set; }
        public decimal rendimento_alcool { get; set; }
        public decimal rendimento_gasolina { get; set; }
        public decimal VerificaAlcool { get; set; }
        public decimal VerificaGasolina { get; set; }
        public string abastece { get; set; }
        public const decimal irrelevante = 5;




        public string VerificaConsumo()
        {
            VerificaAlcool = (alcool * rendimento_alcool)+irrelevante;
            VerificaGasolina = gasolina * rendimento_gasolina;

         

            if (VerificaAlcool < VerificaGasolina)
            {
              abastece = "Viavel Abastecer com Alcool";
            }

            else
            {
                abastece = "Viavel abastecer com Gasolina";
            }



            return abastece;


        }






    }
}

URI-C#/Frota-Taxi/Frota-Taxi/Controllers/FrotaTaxiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Frota_Taxi.Models;

namespace Frota_Taxi.Controllers
{
    public class FrotaTaxiController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}


        public IActionResult Frota()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Frota(Frota nova)
        {
            nova.VerificaConsumo();

            return View(nova);
        }








    }
}

URI-C#/Frota-Taxi/Frota-Taxi/Views/FrotaTaxi/Frota.cshtml
@model Frota_Taxi.Models.Frota

@{
    ViewData["Title"] = "Frota";
}



<script src="http://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>

<div class="jumbotron">
    <h4><b>Frota de Taxi </b></h4>
    <p>A Companhia de Táxi Tabajara (CTT) é uma das maiores empresas de transporte do país. Possui uma vasta frota de carros e opera em todas as grandes cidades. Recentemente a CTT modernizou a sua frota, adquirindo um lote de 500 carros bi-combustíveis (carros que podem utilizar como combustível tanto álcool quanto gasolina). Além do maior conforto para os passageiros e o menor gasto com manutenção, com os novos carros é possível uma redução adicional de custo: como o preço da gasolina está sujeito a variações muito bruscas e pode ser vantagem, em certos momentos, utilizar álcool como combustível. Entretanto, os carros possuem um melhor desempenho utilizando gasolina, ou seja, em geral, um carro percorre mais quilômetros por litro de gasolina do que por litro de álcool.</p>
    <p>Você deve escrever um programa que, dados o preço do litro de álcool, o preço do litro de gasolina e os quilômetros por litro que um carro bi-combustível realiza com cada um desses combustíveis, determine se é mais econômico abastecer os carros da CTT com álcool ou com gasolina. No caso de não haver diferença de custo entre abastecer com álcool ou gasolina a CTT prefere utilizar gasolina.</p>
    <p><h4><b>Entrada</b></h4></p>
    <p>A entrada é composta por uma linha contendo quatro números reais com precisão de duas casas decimais A e G (0.01 ≤ A, G ≤ 10.00) Ra e Rg (0.01 ≤ Ra , Rg ≤ 20.00) representando respectivamente o preço por litro do álcool, o preço por litro da gasolina, o rendimento (km/l) do carro utilizando álcool e o rendimento (km/l) do carro utilizando gasolina.</p>
    <p>A entrada deve ser lida do dispositivo de entrada padrão (normalmente o teclado). </p>
    <p><h4><b>Saida</b></h4></p>
    <p>A saída deve ser composta por uma única linha contendo o caractere ‘A’ se é mais econômico abastecer a frota com álcool ou o caractere ‘G’ se é mais econômico ou indiferente abastecer a frota com gasolina</p>
    <p>A saída deve ser escrita no dispositivo de saída padrão (normalmente a tela)</p>
</div>

@*@using (Html.BeginForm("SuaActionX", "SeuControllerX", FormMethod.Post))
    {
        // ...
    }*@


<div class="row">
    <div class="col-md-4">

        @using (Html.BeginForm("Frota", "FrotaTaxi", FormMethod.Post, new {id = "Frota" }))
        {

    
            <div class="form-group">
                @Html.Label("Preco Alcool:", "Preco Alcool:")
                @Html.TextBoxFor(model => model.alcool, new { @class = "form-control", id = "Alcool", required = "required" })
            </div>



            <div class="form-group">
                @Html.Label("Preco Gasolina:", "Preco Gasolina:")
                @Html.TextBoxFor(model => model.gasolina, new { @class = "form-control", id = "Gasolina", required = "required" })
            </div>


            <div class="form-group">
                @Html.Label("Rendimento Alcool:", "Rendimento Alcool:")
                @Html.TextBoxFor(model => model.rendimento_alcool, new { @class = "form-control", id = "RendimentoAlcool", required = "required" })
            </div>


            <div class="form-group">
                @Html.Label("Rendimento Gasolina:", "Rendimento Gasolina:")
                @Html.TextBoxFor(model => model.rendimento_gasolina, new { @class = "form-control", id = "RendimentoGasolina", required = "required" })
            </div>


            <div class="form-group">
                <input type="submit" value="Executar" class="btn btn-danger" id="Executa" />
            </div>


            <div class="form-group">
                @Html.Label("Resultado:", "Resultado:")


                @Html.DisplayFor(m => m.abastece, new { @class = "form-control" })


            </div>


        }


    </div>

</div>

URI-C#/Frota-Taxi/Frota-Taxi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Frota_Taxi</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Frota_Taxi</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Frota_Taxi</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>