URI-C#/Carrega/Carrega/Models/Carrega.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Carrega.Models
{
    public class Circuito
    {
        public int Bit1 { get; set; }
        public int Bit2 { get; set; }
        public int Bit3 { get; set; }
        public int Bit4 { get; set; }
        public int Bit5 { get; set; }


        public int ConverteBinario()
        {

            Bit1 = Bit2 - Bit3;

            return Bit1;

        }



    }
}

URI-C#/Carrega/Carrega/Models/ErrorViewModel.cs
using System;

namespace Carrega.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

URI-C#/Carrega/Carrega/Controllers/CarregaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Carrega.Models;

namespace Carrega.Controllers
{
    public class CarregaController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}

   
        public IActionResult Carregando()
        {

            return View();
        }


        [HttpPost]
        public IActionResult Carregando(Circuito carregando)
        {
            carregando.ConverteBinario();

            return View(carregando);
        }






    }
}

URI-C#/Carrega/Carrega/Views/Carrega/Carregando.cshtml
@model Carrega.Models.Circuito

@{
    ViewData["Title"] = "Carregando";
}

<script src="http://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>

<div class="jumbotron">
    <h1>Bootstrap Tutorial</h1>
    <p>Bootstrap is the most popular HTML, CSS...</p>
</div>

@*@using (Html.BeginForm("SuaActionX", "SeuControllerX", FormMethod.Post))
    {
        // ...
    }*@


<div class="row">
    <div class="col-md-4">

        @using (Html.BeginForm("Carregando", "Carrega", FormMethod.Post, new { id = "teste" }))
        {

            @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
            <div class="form-group">
                @Html.Label("Bit 01:", "Bit 01:")
                @Html.TextBoxFor(model => model.Bit2, new { @class = "form-control", id = "Numero01",required="required" })
            </div>



            <div class="form-group">
                @Html.Label("Bit 02:", "Bit 02:")
                @Html.TextBoxFor(model => model.Bit3, new { @class = "form-control", id = "Numero02",required="required" })
            </div>


            <div class="form-group">
                <input type="submit" value="Executar" class="btn btn-danger" id="Executa" />
            </div>


            <div class="form-group">
                @Html.Label("Resultado:", "Resultado:")


                @Html.DisplayFor(m => m.Bit1, new { @class = "form-control" })


            </div>




        }


    </div>






</div>